**HERE WILL BE AN EXPLINATION OF**

```
1- Definition of Numpy and why do we use it 

2- Creating arrays

3- Slicing 

4- Datatypes in Numpy
```

**Why do we use NumPY?**

we can use lists to represent arrays but it works so slow in that -> NumPy aims to provide an array object that is up to 50x faster than traditional Python lists

the array object in numpy is called **ndarray**

**Why is NumPy faster than lists?**

* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently

In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])

print(type(arr))

<class 'numpy.ndarray'>


to build **ndarray** u can pass any kind of containers to array()  

fot pervious Example we used 1-D array , if u wanna convert it to 2-D array u will add another container argument

In [4]:
two_D = np.array([(1,2,3,4) , (1,2,3,4)])

print(two_D)

[[1 2 3 4]
 [1 2 3 4]]


**3-D array**

is a collection of 2-D arrays -> u can think of it as multiple sheets of paper 

In [5]:
thee_D = np.array([[[1,2,3],[4,5,6]], [[1,2,3] , [4,5,6]]])

print(thee_D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


To check the array Dimention u will be using **ndim**

In [6]:
print(arr.ndim)
print(two_D.ndim)
print(thee_D.ndim)

1
2
3


U will be using normal accessing for any dimantion but the higher one u will be using nxm indecies 

In [7]:
print(two_D[1 , 1]) # that means print the 2nd element in the 2nd coulmn

2


**Slicing Arrays**

slicing in pythong means take elements from index to another 

* using simple one [start : end]

* u can also do it by [start : end : number_of_steps]
-------------------------------------------------------------------
- if u did not pass the start it will automaticlly starts from 0        

- if u did not pass the end it will continue till the end of array 

- if u ded not specify the number of steps it will be 1 by default

In [8]:
array = np.array([1,2,3,4,5,6,7,8,9,10]) 


print(array[4:])
print(array[:5])
print(array[::2])
print(array[::3])

[ 5  6  7  8  9 10]
[1 2 3 4 5]
[1 3 5 7 9]
[ 1  4  7 10]


**Datatypes in NumPy**

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

and to check datatype u will use **dtype** keyword

```you can also define the datatype of the array```


In [11]:
print(two_D.dtype)

define = np.array([1,2,3,4] , dtype = 'S')

print(define)
print(define.dtype)

int64
[b'1' b'2' b'3' b'4']
|S1


**Converting Datatype of existing array**

1- make a copy of the array by using **astype()** method

2- specify the datatype of the new array

In [13]:
farr = np.array([1.1 , 2.1 , 3.1])

narr = farr.astype('i')

print(farr)
print(narr)

# ---------------------------------------------------
# changing to boolean array

norm = np.array([1,0,3])

boolean = norm.astype(bool)

print(boolean)
print(boolean.dtype)

[1.1 2.1 3.1]
[1 2 3]
[ True False  True]
bool
