**HERE WILL BE AN EXPLINATION OF**

```
1- copy and view functions

2- array shape 

3- array reshape

4- array iterating 

5- joining 

6- splitting 

7- searching

8- sorting

9- filtering 
```

**The difference between copy and view** 

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [1]:
import numpy as np 

In [ ]:
array = np.array([10,20,30,40,50,60])
x= array.copy()

array[0] = 5

print(x)
print(array)
# u will see x is not affected cause it is a copy from the original array , any changes that may cause to the original array will never affect it 

[10 20 30 40 50 60]
[ 5 20 30 40 50 60]


In [ ]:
y = array.view()

array[0] =10

print(array)
print(y)
# as u can see the change that cause to the original array has been caused to the copy 
# they share the same data buffer in memory
# so if u also changed any value of y then the original array will be affected either

[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [4]:
y[1] = 15

print(array)
print(y)

[10 15 30 40 50 60]
[10 15 30 40 50 60]


**array shape**

define -> the shape of an array is the number of elements in each dimension 

to know it u will be using **shape** keyword of an array

In [8]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[1,2,3,4] , [1,2,3,4] , [1,2,3,4,]])b

print(arr.shape)
print(arr2.shape)

(2, 4)
(3, 4)


**Reshape**

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension. 

using **reshape(number_of_arrays , number_of_elements)** func

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 

new2 = arr.reshape(4,3) # this to convert from 1-D to 2-D array 

new3 = arr.reshape(2,3,2) # convert from 1-D to 3-D which means the new container will have 2 arrays contains 3 arrays each one got 2 elements

print(new2)
print(new3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


as long as the elements required for reshaping are equal in both shapes -> **We can reshape any element**

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements

**Flatteing the array** 

converting multidimensional array to 1-D array by using  **reshape(-1)**

**Iterating Arrays**

just going through the elements of a simple array 

* using 1 loop will return row by row

* if u wanna return a scalar or specific element u will iterate in each dimension

In [15]:
arr = np.array([1,2,3])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr:
    print(i)
print('-------------------------------')
for i in arr2:
    print(i) # that will go through all the rows 
print('-------------------------------')
for i in arr3:
    print(i)



1
2
3
-------------------------------
[1 2 3]
[4 5 6]
-------------------------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [16]:
for x in arr3:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**Iterating Arrays Using nditer()**

It is a helping function that can be used from very basic to very advanced iterations. 
It solves some basic issues which we face in iteration .

n basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality

In [17]:
for i in np.nditer(arr3):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


**Joining numpy array**

joining here differs from SQL it means putting the content of 2 aarrays in 1 (**concatenate**) 

* concatenate() method

* stack() method -> puts them above each other if u want them to be concatenated in 1 row use **axis=1**

* hstack() method -> stack along rows 

* vstack method -> stack along columns 

In [24]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])


array3 = np.concatenate((array1,array2))
arr3 = np.concatenate((arr1,arr2),axis=1)



print(array3)
print(arr3)

[1 2 3 4 5 1 2 3 4 5]
[[1 2 5 6]
 [3 4 7 8]]


**Split**

* this is the reverse operation of joining -> We use array_split() for splitting arrays

* If you split an array into specified number of  arrays, you can access them from the result just like any array element

In [29]:
arr4 = np.array_split(arr3 , 2)

print(arr4)
print('--------------------------------')
print(arr[0])
print(arr[1])

[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]
--------------------------------
1
2


**Searching Arrays**

using where() method 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
arr1 = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr == 4)
x1 = np.where(arr1%2 ==0 )


print(x) # will print all the values of that locates number 4
print(x1) # will print all even numbers

(array([3, 5, 6]),)
(array([0, 1, 4]),)


**Search Sorted**

searchsorted() method will perform binary search in the array and return the index where the specified value would be inserted to maintain the search order 
it assumes that u r working on a sorted array 


In [34]:
arr = np.array([1,2,3,4,5,6])

x = np.searchsorted(arr,6)
y = np.searchsorted(arr, [2,4,6])

print(x)
print(y)

5
[1 3 5]


**Sorting Arrays**

using the basic sort() function

In [35]:
arr = np.array([0,2,1,3,6,4,5])

arr = np.sort(arr)

print(arr)

[0 1 2 3 4 5 6]


In [36]:
arr = np.array([True, False, True])

arr = np.sort(arr)

print(arr)

[False  True  True]
